# Generated by Django 5.2.16 on 2026-07-13 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('hours', models.IntegerField()),
                ('course_days', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Pending', 'Pending'), ('Done', 'Done')], max_length=20)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicperiod')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.cohort')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.lecturer')),
            ],
        ),
    ]
