# Generated by Django 5.2.16 on 2026-07-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workload',
            name='generated_schedule',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workload',
            name='course_days',
            field=models.CharField(help_text='Example: Sunday,Thursday', max_length=100),
        ),
    ]
