# Generated by Django 5.2.16 on 2026-07-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0002_workload_generated_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workload',
            name='hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
