# Generated by Django 5.2.16 on 2026-07-22 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_academicperiod_options_alter_cohort_options_and_more'),
        ('workload', '0003_alter_workload_hours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workload',
            options={'ordering': ['-id'], 'verbose_name': 'Teaching Workload', 'verbose_name_plural': 'Teaching Workloads'},
        ),
        migrations.AlterField(
            model_name='workload',
            name='academic_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workloads', to='academics.academicperiod'),
        ),
        migrations.AlterField(
            model_name='workload',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workloads', to='academics.cohort'),
        ),
        migrations.AlterField(
            model_name='workload',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workloads', to='academics.course'),
        ),
        migrations.AlterField(
            model_name='workload',
            name='course_days',
            field=models.CharField(help_text='Example: Monday,Thursday', max_length=100),
        ),
        migrations.AlterField(
            model_name='workload',
            name='generated_schedule',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='workload',
            name='hours',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='workload',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workloads', to='academics.lecturer'),
        ),
        migrations.AlterField(
            model_name='workload',
            name='status',
            field=models.CharField(blank=True, choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Pending', 'Pending'), ('Done', 'Done')], editable=False, max_length=20),
        ),
    ]
