# Generated by Django 5.2.16 on 2026-08-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0004_alter_workload_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workload',
            name='hours',
            field=models.IntegerField(blank=True, editable=False, help_text='Notional teaching hours (credits x 15).', null=True),
        ),
    ]
