# Generated by Django 5.2.16 on 2026-08-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_academicperiod_unique_together_and_more'),
        ('workload', '0005_alter_workload_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='workload',
            name='co_lecturers',
            field=models.ManyToManyField(blank=True, related_name='co_workloads', to='academics.lecturer'),
        ),
        migrations.AddField(
            model_name='workload',
            name='duration_weeks',
            field=models.PositiveIntegerField(blank=True, help_text="Leave blank to use the standard block length for the course's credit value.", null=True),
        ),
    ]
