# Generated by Django 5.2.16 on 2026-07-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('lecturer', 'Lecturer'), ('representative', 'Class Representative')], default='lecturer', max_length=20),
        ),
    ]
