# Generated by Django 5.2.16 on 2026-07-23 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_cohort_representative'),
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturerAccountAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecturer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_assignment', to='academics.lecturer')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'lecturer'}, on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_account_assignment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lecturer Account Assignment',
                'verbose_name_plural': 'Lecturer Account Assignments',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RepresentativeAccountAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='representative_assignment', to='academics.cohort')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'representative'}, on_delete=django.db.models.deletion.CASCADE, related_name='representative_account_assignment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Representative Account Assignment',
                'verbose_name_plural': 'Representative Account Assignments',
                'ordering': ['-id'],
            },
        ),
    ]
