# Generated by Django 5.2.16 on 2026-08-17 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_backfill_links_before_dropping_assignments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representativeaccountassignment',
            name='cohort',
        ),
        migrations.RemoveField(
            model_name='representativeaccountassignment',
            name='user',
        ),
        migrations.DeleteModel(
            name='LecturerAccountAssignment',
        ),
        migrations.DeleteModel(
            name='RepresentativeAccountAssignment',
        ),
    ]
