# Generated by Django 5.2.16 on 2026-07-22 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicperiod',
            options={'ordering': ['-academic_year']},
        ),
        migrations.AlterModelOptions(
            name='cohort',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='lecturer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='cohort',
            name='representative',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'representative'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohort', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.program'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='academics.program'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='qualification',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='program',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academics.faculty'),
        ),
        migrations.AlterUniqueTogether(
            name='academicperiod',
            unique_together={('academic_year', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='cohort',
            unique_together={('program', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('faculty', 'name')},
        ),
    ]
