# Generated by Django 5.2.16 on 2026-07-22 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_academicperiod_options_alter_cohort_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='representative',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'representative'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representing_cohort', to=settings.AUTH_USER_MODEL),
        ),
    ]
