# Generated by Django 5.2.16 on 2026-08-16 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_lecturer_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='academicperiod',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='academicperiod',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_periods', to='academics.cohort'),
        ),
        migrations.AlterUniqueTogether(
            name='academicperiod',
            unique_together={('academic_year', 'semester', 'cohort')},
        ),
    ]
